Final branch
MarkoKermi/metrics_webapp pull request #5
Opened 2023-03-16 15:05 UTC by MarkoKermi

- [ ] I fetched the countries data from https://restcountries.com/

- [ ] In the home page you can find a cards with all countries and also a dropdown menu where you can select the continents. 
- [ ] When you click the cards, a new detail page is showing where you can see the details of all countries (population, flag, capitol city, area and time zone.)
- [ ] You can see the walkthrough video of the web app [here]( ).

2023-03-16 19:09 UTC, VICTOR-CHUKWU requested changes
Hi @MarkoKermi , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-16 19:09 UTC, VICTOR-CHUKWU commented on README.md
> +  - The project is MIT licensed, please refer to the License section
- [ ] your MIT  link is broken, kindly fix it

2023-03-16 19:09 UTC, VICTOR-CHUKWU commented on README.md
> +- I have added a [Video Presentaition](https://www.loom.com/share/0fd72d02c23b4c6e8563e82909a55463)
- [ ] while showing the piece of code you are proud of, your screen was stuck to your browser not showing your vscode, kindly add a screen showing your vscode while describing the piece of code your are proud of

2023-03-17 08:08 UTC, peterrobert commented on README.md
> +  - The project is MIT licensed, please refer to the License section
This change has been done well

2023-03-17 08:10 UTC, peterrobert commented on README.md
> +- I have added a [Video Presentaition](https://www.loom.com/share/0fd72d02c23b4c6e8563e82909a55463)
This change has been done well

2023-03-17 08:11 UTC, peterrobert approved these changes
Hi @MarkoKermi, 


### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 08:12 UTC, merged